os:
  - linux
  - windows
language: node_js
cache: false
node_js:
- node
  - 10
  - 12
  - node


stages:
  - name: test
  - name: deploy
    if: (NOT type IN (pull_request)) AND ( branch = master OR tag =~ ^v[0-9] )

jobs:
  include:
    - stage: deploy
      name: deploy
      script: .travis/deploy_npm
  
